name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: Ashutosh9110
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: GITHUB_OUTPUT
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Snake SVG Output
        run: echo "SNAKE_SVG_PATH=${{ steps.snake-gif.outputs.svg_out_path }}" >> $GITHUB_ENV
